[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_nft_project = "6HHRqdp2BNWoswpdt3WLmMsBtLBuVdJ2GUjG9PMmDTuP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
